version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - data:/data/db
      - config:/data/configdb
    ports:
      - 27017:27017

volumes:
  data:
  config:
